# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!
# TODO: This format file is obsolete, consider migrating to JSON.

{ fetchNuGet }:
[
  (fetchNuGet {
    pname = "docfx";
    version = "2.77.0";
    hash = "sha256-wIoKciEMeE8WOysMSmaoPvMtyPi8M0fPF9nkvPss6Js=";
  })
  (fetchNuGet {
    pname = "dotnet-format";
    version = "5.1.250801";
    hash = "sha256-kHttHcqmrB2G2du7bCfwertwVBBCiSVzICFd70VnEcQ=";
  })
  (fetchNuGet {
    pname = "dotnet-repl";
    version = "0.1.216";
    hash = "sha256-JHatCW+hl2792S+HYeEbbYbCIS+N4DmOctqXB/56/HU=";
  })
  (fetchNuGet {
    pname = "JetBrains.ReSharper.GlobalTools";
    version = "2024.1.4";
    hash = "sha256-DYaYeWMKUREqiKd7aLQo2gnHEmMvXS1YiuuxPVZ6xsw=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyInjection.Abstractions";
    version = "8.0.2";
    hash = "sha256-UfLfEQAkXxDaVPC7foE/J3FVEXd31Pu6uQIhTic3JgY=";
  })
  (fetchNuGet {
    pname = "Newtonsoft.Json";
    version = "13.0.3";
    hash = "sha256-hy/BieY4qxBWVVsDqqOPaLy1QobiIapkbrESm6v2PHc=";
  })
  (fetchNuGet {
    pname = "OrchardCore.Abstractions";
    version = "1.8.3";
    hash = "sha256-qf4wxbLMxPTjGuOwI4iaGayhQrJwZ/YEAncxOOY5n/w=";
  })
  (fetchNuGet {
    pname = "Roslynator.DotNet.Cli";
    version = "0.8.9";
    hash = "sha256-tcCPAw8PmnXRTr9oGO8Oph0hGCC55NMOPVno7lHjhkE=";
  })
  (fetchNuGet {
    pname = "SonarAnalyzer.CSharp";
    version = "9.28.0.94264";
    hash = "sha256-lG8+16cWHYNhO0MFjUHv0zQGj5mipRmUr57z3CaO1wk=";
  })
  (fetchNuGet {
    pname = "StyleCop.Analyzers";
    version = "1.1.118";
    hash = "sha256-CjC1f5z0sP15F6FeXqIDOtZLHqgjmQTzpsIrRkxXREI=";
  })
  (fetchNuGet {
    pname = "ZString";
    version = "2.5.1";
    hash = "sha256-7sENkAu0OzdUPV/ts60DfsaJdY+hg+2Bm7EELMvhl3Y=";
  })
]
